# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: Pack
    type: boolean
    default: true
  - name: Sign
    type: boolean
    default: true

pool:
  vmImage: windows-latest

trigger:
  branches:
    include:
      - main
pr: none

jobs:
  - job: EntraPowerShellCIBuild
    displayName: Entra PowerShell CI Build
    timeoutInMinutes: 840
    steps:
      - template: ./common-templates/install-tools.yml    
      - template: ./common-templates/security-pre-checks.yml

      - template: ./generation-templates/generate_adapter-migrate.yml
        parameters:
          Sign: ${{ parameters.Sign }}

      - ${{ if and(eq(parameters.Pack, true), eq(parameters.Sign, true)) }}:
          - template: ./common-templates/esrp/codesign-nuget-migrate.yml
            parameters:
              FolderPath: "$(Build.ArtifactStagingDirectory)"
              Pattern: "Microsoft.Graph.Entra.*.nupkg"

          - task: PublishBuildArtifacts@1
            displayName: Publish Module Artifacts
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
              publishLocation: "Container"

          - task: NuGetCommand@2
            displayName: Publish NuGet to preview feed
            inputs:
              command: push
              packagesToPush: $(Build.ArtifactStagingDirectory)/**/Microsoft.Graph.Entra.*.nupkg
              publishVstsFeed: $(PROJECT_NAME)/$(PREVIEW_FEED_NAME)
              allowPackageConflicts: true

      - template: ./common-templates/security-post-checks.yml
