trigger: none
resources:
  repositories:
  - repository: templates
    type: git
    name: OneBranch.Pipelines/GovernedTemplates
    ref: refs/heads/main
  pipelines:
  - pipeline: _EntraPowerShell-Release-Build
    trigger: none
    source: EntraPowerShell-Release-Build
    project: One
extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    stages:
    - stage: Prod_PS_Gallery_Deploy
      displayName: PS Gallery Deploy
      variables:
        ob_release_environment: Production
      dependsOn: []
      jobs:
      - job: ApprovalService_Job
        displayName: 'Approval Service'
        pool:
          type: release
        steps:
          - download: _EntraPowerShell-Release-Build
          - task: vsrm-ev2.vss-services-ev2.adm-release-task.ExpressV2Internal@1
            inputs:
              UseServerMonitorTask: true
              EndpointProviderType: ApprovalService
              ApprovalServiceEnvironment: Production
              ServiceRootLocation: 'LinkedArtifact'
              RolloutSpecType: ' '
              ServiceRootPath: ' '
              RolloutSpecPath: ' '

      - job: PsGallery_Push
        displayName: Push to PS Gallery
        pool:
          type: server
        timeoutInMinutes: 6120
        steps:
        - task: powershell@2
          inputs:
            targetType: inline
            script: |
              Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Graph.Entra -Verbose
              Publish-Module -NuGetApiKey $env:NuGetApiKey -Path $(Build.ArtifactStagingDirectory)/modules/Microsoft.Graph.Entra.Beta -Verbose
            pwsh: false
        dependsOn: ApprovalService_Job