# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
pr: none

variables:
  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2022/vse2022:latest'
parameters:
  - name: Pack
    type: boolean
    default: true
  - name: Sign
    type: boolean
    default: true
resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main

extends:
  template: v2/OneBranch.Official.CrossPlat.yml@templates
  parameters:
    featureFlags:
      WindowsHostVersion: 1ESWindows2022
    stages:
    - stage: build
      jobs:
      - job: EntraPowerShellCIBuild
        displayName: Entra PowerShell CI Build
        timeoutInMinutes: 840
        pool:
          type: windows
        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)/out'
        steps:
          - template: .azure-pipelines/common-templates/install-tools.yml@self
          - template: .azure-pipelines/common-templates/security-pre-checks.yml@self

          - template: .azure-pipelines/generation-templates/generate_adapter-migrate.yml@self
            parameters:
              Sign: ${{ parameters.Sign }}

          - ${{ if and(eq(parameters.Pack, true), eq(parameters.Sign, true)) }}:
              - template: .azure-pipelines/common-templates/esrp/codesign-nuget-migrate.yml@self
                parameters:
                  FolderPath: "$(Build.ArtifactStagingDirectory)"
                  Pattern: "Microsoft.Graph.Entra.*.nupkg"

              - task: PublishBuildArtifacts@1
                displayName: Publish Module Artifacts
                inputs:
                  PathtoPublish: "$(Build.ArtifactStagingDirectory)"
                  ArtifactName: "drop"
                  publishLocation: "Container"

              - task: NuGetCommand@2
                displayName: Publish NuGet to preview feed
                inputs:
                  command: push
                  packagesToPush: $(Build.ArtifactStagingDirectory)/**/Microsoft.Graph.Entra.*.nupkg
                  publishVstsFeed: $(PROJECT_NAME)/$(PREVIEW_FEED_NAME)
                  allowPackageConflicts: true

          - template: .azure-pipelines/common-templates/security-post-checks.yml@self